name: Pelican site CI

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - name: check out code
        uses: actions/checkout@v4
      - name: show content
        run: ls -la
      - name: setup venv
        uses: getsentry/action-setup-venv@v2.1.1
        id: venv
        with:
          python-version: 3.10.7
          cache-dependency-path: |
            requirements.txt
          install-cmd: pip install -r requirements.txt